//
//  FeedCollectionViewController.swift
//  Outfit Selection
//
//  Created by Denis Bystruev on 27.09.2021.
//  Copyright © 2021 Denis Bystruev. All rights reserved.
//

import IBPCollectionViewCompositionalLayout

class FeedCollectionViewController: LoggingViewController {
    // MARK: - Outlets
    @IBOutlet weak var feedCollectionView: UICollectionView!
    
    // MARK: - Stored Properties
    let sections = [
        FeedKind.brands,
        FeedKind.newItems,
        FeedKind.sale,
    ] + Occasion.selectedNames.map { _ in .occasions }
        
    let numberOfItemsInSection = 42
    
    // MARK: - Custom Methods
    /// Compose layout for feed collection view
    /// - Returns: collection view layout for feed collection view
    private func generateLayout() -> UICollectionViewLayout {
        // Deifine the item size
        let itemSize = NSCollectionLayoutSize(
            widthDimension: .fractionalWidth(1),
            heightDimension: .fractionalHeight(1)
        )
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        
        // Define the group size
        let groupSize = NSCollectionLayoutSize(
            widthDimension: .absolute(120 * CGFloat(numberOfItemsInSection)),
            heightDimension: .absolute(206)
        )
        let group = NSCollectionLayoutGroup.horizontal(
            layoutSize: groupSize,
            subitem: item,
            count: numberOfItemsInSection
        )
        
        // Define the section and layout sizes
        let section = NSCollectionLayoutSection(group: group)
        let layout = UICollectionViewCompositionalLayout(section: section)
        return layout
    }
    
    // MARK: - UIViewController Inherited Methods
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Set self as data source for the feed collection view
        feedCollectionView.dataSource = self
        
        // Register collection view cells
        feedCollectionView.register(BrandCollectionViewCell.nib, forCellWithReuseIdentifier: BrandCollectionViewCell.reuseId)
        feedCollectionView.register(
            FeedItemCollectionViewCell.self,
            forCellWithReuseIdentifier: FeedItemCollectionViewCell.reuseId
        )
        
        // Use the layout generated by custom method
        feedCollectionView.setCollectionViewLayout(generateLayout(), animated: false)
        
        debug("DEBUG: \(sections.count) item groups: \(sections)")
    }
}
