//
//  FeedCollectionViewController.swift
//  Outfit Selection
//
//  Created by Denis Bystruev on 27.09.2021.
//  Copyright © 2021 Denis Bystruev. All rights reserved.
//

import IBPCollectionViewCompositionalLayout

class FeedCollectionViewController: LoggingViewController {
    // MARK: - Outlets
    @IBOutlet weak var feedCollectionView: UICollectionView!
    
    // MARK: - Stored Properties
    let sections = [
        FeedKind.brands,
        FeedKind.newItems,
        FeedKind.sale,
    ] + Occasion.selectedNames.map { _ in .occasions }
        
    let numberOfItemsInSection = 42
    
    // MARK: - Custom Methods
    /// Compose layout for feed collection view
    /// - Returns: collection view layout for feed collection view
    private func generateLayout() -> UICollectionViewLayout {
        // Define cell spacing
        let spacing: CGFloat = 8
        
        // Define the item size
        let itemSize = NSCollectionLayoutSize(
            widthDimension: .fractionalWidth(1),
            heightDimension: .fractionalHeight(1)
        )
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        item.contentInsets = NSDirectionalEdgeInsets(
            top: 0,
            leading: spacing,
            bottom: 0,
            trailing: spacing
        )
        
        // Define the group size
        let groupSize = NSCollectionLayoutSize(
            widthDimension: .absolute(FeedItemCollectionViewCell.width * CGFloat(numberOfItemsInSection)),
            heightDimension: .absolute(FeedItemCollectionViewCell.height)
        )
        let group = NSCollectionLayoutGroup.horizontal(
            layoutSize: groupSize,
            subitem: item,
            count: numberOfItemsInSection
        )
        group.contentInsets = NSDirectionalEdgeInsets(
            top: spacing,
            leading: spacing,
            bottom: 0,
            trailing: spacing
        )
        
        // Define section header size
        let headerSize = NSCollectionLayoutSize(
            widthDimension: .fractionalWidth(1),
            heightDimension: .absolute(FeedSectionHeaderView.height)
        )
        let header = NSCollectionLayoutBoundarySupplementaryItem(
            layoutSize: headerSize,
            elementKind: UICollectionView.elementKindSectionHeader,
            alignment: .top
        )
        
        // Define the section size
        let section = NSCollectionLayoutSection(group: group)
        section.boundarySupplementaryItems = [header]
        section.interGroupSpacing = spacing
        section.orthogonalScrollingBehavior = .continuous
        
        // Define the layout size
        let layout = UICollectionViewCompositionalLayout(section: section)
        
        return layout
    }
    
    // MARK: - UIViewController Inherited Methods
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Set self as data source for the feed collection view
        feedCollectionView.dataSource = self
        
        // Register collection view cells and header
        feedCollectionView.register(BrandCollectionViewCell.nib, forCellWithReuseIdentifier: BrandCollectionViewCell.reuseId)
        feedCollectionView.register(
            FeedItemCollectionViewCell.self,
            forCellWithReuseIdentifier: FeedItemCollectionViewCell.reuseId
        )
        feedCollectionView.register(
            FeedSectionHeaderView.self,
            forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader,
            withReuseIdentifier: FeedSectionHeaderView.reuseId
        )
        
        // Use the layout generated by custom method
        feedCollectionView.setCollectionViewLayout(generateLayout(), animated: false)
        
        debug("DEBUG: \(sections.count) item groups: \(sections)")
    }
}
